# R programming

The link for my resource is [Here](https://www.youtube.com/watch?v=_V8eKsto3Ug)

#### Data types in R:
* Numeric (integer, single and double)
* Character
* Logical
* Complex number
* Raw

#### Data Structures:
* Vectors
* Matrix
* Data Frame
* List

**Vectors**
* one or more numbers in a 1 dimentional array.
* data are all the same data types.
* R's basic data object

**Matrix**
* has rows and columns
* 2D data
* same length
* same data class
* columns are not named

**Array**
* 3 or more dimentions

**Data Frames**
* Can have vectors of multiple types.
* all same length
* Closest R equivalence to spreadsheet
* Has special functions to work with these

**List**
* Most flexible
* Ordered collection of elements
* can contain any classes, length or structures.
* list can include lists
* its hard to work with these.

#### Coersion
Changing data object type of one type to the other.

In [1]:
# Data Types
n2 <- 1.5
n2
typeof(n2)

l2 <- F
l2
typeof(l2)


[1] 1.5

[1] "double"

[1] FALSE

[1] "logical"

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] TRUE

In [2]:
#Data Structures

v3 <- c(TRUE, TRUE, FALSE, FALSE, TRUE)      #c is concatinate or collect
v3
is.vector(v3)

# Matrix

m1 <- matrix(c(T, T, F, F, T, F), nrow = 2)   # nrow is number of rows.
m1


m2 <- matrix(c("a", "b", 
               "c", "d"), 
               nrow = 2,
               byrow = T)
m2

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] TRUE

[,1] [,2]  [,3] 
[1,] TRUE FALSE  TRUE
[2,] TRUE FALSE FALSE

[,1] [,2]
[1,] a    b   
[2,] c    d

In [3]:
#Arrays. Gotta see this in R studio
# Give data, then dimemensions (rows, columns, tables)
a1 <- array(c( 1:24), c(4, 3, 2))    # c(1 through 24), c(rows, columns, tables)
a1

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

In [4]:
#Data Frame

vNumeric   <- c(1, 2, 3)
vCharacter <- c("a", "b", "c")
vLogical   <- c(T, F, T)

dfa <- cbind(vNumeric, vCharacter, vLogical)
dfa  # Matrix of one data type


#The following is for making the data type their original data type.
df <- as.data.frame(cbind(vNumeric, vCharacter, vLogical))
df  # Makes a data frame with three different data types

vNumeric vCharacter vLogical
[1,] 1        a          TRUE    
[2,] 2        b          FALSE   
[3,] 3        c          TRUE

vNumeric vCharacter vLogical
1 1        a          TRUE    
2 2        b          FALSE   
3 3        c          TRUE

In [6]:
# List

o1 <- c(1, 2, 3)
o2 <- c("a", "b", "c", "d")
o3 <- c(T, F, T, T, F)

list1 <- list(o1, o2, o3)
list1


list2 <- list(o1, o2, o3, list1)  # Lists within lists!
list2

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

[[4]]
[[4]][[1]]
[1] 1 2 3

[[4]][[2]]
[1] "a" "b" "c" "d"

[[4]][[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

#### Coercion

In [9]:
# Automatic coercion

# Goes to "least restrictive" data type

(coerce1 <- c(1, "b", TRUE))   # the bracket around this will print the coerce1
typeof(coerce1)

[1] "1"    "b"    "TRUE"

[1] "character"

In [13]:
a <- 5
a

typeof(a)

[1] 5

[1] "double"

In [12]:
(b <- as.integer(a))
typeof(b)

[1] 5

[1] "integer"

In [17]:
#Character to numeric

(coerce4 <- c("1", "2", "3"))
typeof(coerce4)

(coerce5 <- as.numeric(coerce4))
typeof(coerce5)

[1] "1" "2" "3"

[1] "character"

[1] 1 2 3

[1] "double"

 ##### Coercing matrix to the data frame.
 There won't be big difference in the structure but there are things we can do with data frame that we can't do with matrix in  R.

In [19]:
(coerce6 <- matrix(1:9, nrow= 3))
is.matrix(coerce6)

(coerce7 <- as.data.frame(coerce6))
is.data.frame(coerce7)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] TRUE

V1 V2 V3
1 1  4  7 
2 2  5  8 
3 3  6  9

[1] TRUE